<?xml version="1.0" encoding="utf-8"?>
<Project>

  <PropertyGroup Label="BasePath">
    <BasePath>$(MSBuildThisFileDirectory)</BasePath>
    <MinimumVisualStudioVersion>18</MinimumVisualStudioVersion>
    <LangVersion>latest</LangVersion>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
