<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.mtp-v2" />
    <PackageReference Include="System.Reactive" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Infrastructure\Exchanges.Common\TradingClient.Exchanges.Common.csproj" />
    <ProjectReference Include="..\..\src\Infrastructure\Exchanges.Gate\TradingClient.Exchanges.Gate.csproj" />
    <ProjectReference Include="..\..\src\Infrastructure\Exchanges.Bitget\TradingClient.Exchanges.Bitget.csproj" />
    <ProjectReference Include="..\..\src\Infrastructure\Persistence\TradingClient.Persistence.csproj" />
  </ItemGroup>

</Project>
